### ISSUE TITLE
Switch from Google Analytics to a more privacy-friendly alternative

### ISSUE THREAD

**Issue by vordenken** [OctoPrint/octoprint.org#3]
There are a few alternatives that are way more privacy-friendly than google analytics.
I will list two I know:
https://matomo.org/
https://plausible.io/

Heres a blogpost listing a few problems with google analytics and why you should consider changing it: https://markosaric.com/degoogleify/#analytics

**Comment by foosel** [comment]
I have my hands full enough that self hosting yet another analytics platform is currently out of the question, and having it cloud based a) costs money and b) does merely shift the privacy concerns to a different company.

If you have an issue with Google Analytics please just block it (like I'm pretty sure you already do), I can completely understand that and will not try to work around it in any way. 

But I do need reliable analytics as a data base for potential sponsors.
