### ISSUE TITLE
[Proposal] Redesign OctoPrint

### ISSUE THREAD

**Issue by Iamlooker** [OctoPrint/octoprint.org#31]
Hello, I am LooKeR 👀. I am an Android Developer and an Amateur Designer.

I came across OctoPrint few days ago while surfing internet, and I found the project to be very interesting. But the website was a little dated in terms of UI. I think it could do with a redesign to a new and modern look 🌟 

I know you guys are a small team, mainly foosel so I understand it might be unfeasible to do this redesign.

Here is a screenshot of the prototype I created for the blog screen, we can work together if you agree to this redesign 😸 

I created the whole design with the context I got from the home page and some blogs. I obviously didn't do any in-person research so I don't know if this design system is on brand with OctoPrint. But we can discuss the actual design system if you guys actually want to do a redesign 😺 

![Blog Screen](https://github.com/OctoPrint/octoprint.org/assets/60404093/fa7eb118-42af-4c34-9789-d11999605c0a)

P.S. I am not a Web Developer so I can only provide design files 😓

**Comment by foosel** [comment]
Hey there, that's a really gracious offer, however it's not something I have the resources for at this time. It's something on the TODO list, but compared to other things it's SO far down on that list it will either take a long time or some required break in the normal day to day to get tackled. Still, thank you again for the offer!
