### ISSUE TITLE
[Request] Update the featured plugins to modern, popular plugins

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/octoprint.org#5]
The plugins featured on the home page are a bit outdated in my opinion, of the 9 on the homepage:
* 2 are disabled, Printer Statistics & M33 Fio (micro 3d printer)
* 1 goes to a 404 (I assume it has been removed from the repo) - Print history
* 2 abandoned/up for adoption - Pushbullet & Slack integration

Could probably just take something like OctoLapse, or bed level visualiser, as they are often things that people spot elsewhere and get questions going. Just thought I'd point it out.

**Comment by foosel** [comment]
Good point, I've updated the list with the current top entries

**Comment by cp2004** [comment]
👍
